minamb/Controllers/FuncionarioController.cs
using minamb.Application;
using minamb.Application.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static minamb.Application.App;

namespace minamb.Controllers
{
    public class FuncionarioController : ManageController
    {
        // GET: Funcionario
        private readonly entidadesEstaticasApp _entidadeEstaticaApp;
        private readonly FuncionarioApp _funcionarioApp;

        public FuncionarioController()
        {
            _entidadeEstaticaApp = new entidadesEstaticasApp();
            _funcionarioApp = new FuncionarioApp();
        }
        public ActionResult Index() 
        {
            ViewBag.Generos = ToJson(_entidadeEstaticaApp.CargarGeneros());
            ViewBag.EstadosCivis = ToJson(_entidadeEstaticaApp.CargarEstadosCivis());
            ViewBag.TipoDocs = ToJson(_entidadeEstaticaApp.CargarTipoDocumento());
            ViewBag.Provincia = ToJson(_entidadeEstaticaApp.CargarProvincias());

            return View();
        }

        public ActionResult Funcionarios()
        {
            ViewBag.Generos = ToJson(_entidadeEstaticaApp.CargarGeneros());
            ViewBag.EstadosCivis = ToJson(_entidadeEstaticaApp.CargarEstadosCivis());
            ViewBag.TipoDocs = ToJson(_entidadeEstaticaApp.CargarTipoDocumento());
            ViewBag.Provincia = ToJson(_entidadeEstaticaApp.CargarProvincias());

            return View();
        }

        [HttpPost]
        public JsonResult CriarFuncionario(FuncionarioDTO funcionario)
        {
            if (ModelState.IsValid)
            {
                return Json(_funcionarioApp.CadastrarFuncionario(funcionario));
            }

            return Json(new AppResultado().Bad($"Erro ao tentar criar Funcionario {": " + ModelState.Values.SelectMany(v => v.Errors).FirstOrDefault().ErrorMessage}"),
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult FiltrarFuncionario(string filtro)
        {
            var res = _funcionarioApp.FiltraFuncionario(filtro, 100);

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PerfilFuncionario(Guid id)
        {
            ViewBag.Cliente = ToJson(_funcionarioApp.FuncionarioById(id));
            return View();
        }
    }
}

minamb/Controllers/RequerenteController.cs
using minamb.Application;
using minamb.Application.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace minamb.Controllers
{
    public class RequerenteController : MasterController
    {
        // GET: Requerente
        private readonly RequerenteApp _requerenteApp;
        private readonly entidadesEstaticasApp _entidadeEstaticaApp;

        public RequerenteController()
        {
            _requerenteApp = new RequerenteApp();
            _entidadeEstaticaApp = new entidadesEstaticasApp();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Requerentes()
        {
            ViewBag.Generos = ToJson(_entidadeEstaticaApp.CargarGeneros());
            ViewBag.EstadosCivis = ToJson(_entidadeEstaticaApp.CargarEstadosCivis());
            ViewBag.TipoDocs = ToJson(_entidadeEstaticaApp.CargarTipoDocumento());
            ViewBag.Provincia = ToJson(_entidadeEstaticaApp.CargarProvincias());

            return View();
        }

        [HttpPost]
        public JsonResult CadastrarRequerente(RequerenteDTO req)
        {
            return Json(_requerenteApp.CadastrarRequerente(req), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult PesquisarRequerentes(string filtro)
        {
            return Json(_requerenteApp.ListarRequerentes(filtro), JsonRequestBehavior.AllowGet);
        }
    }
}

minamb/Controllers/UtilizadoresController.cs
using Microsoft.AspNet.Identity.Owin;
using minamb.Application;
using minamb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static minamb.Application.App;

namespace minamb.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UtilizadoresController : MasterController
    {
        // GET: Utilizadores

        private readonly RolesApp _rolesApp;
        private readonly UtilizadoresApp _utilizadoresApp;

        public UtilizadoresController()
        {
            _rolesApp = new RolesApp();
            _utilizadoresApp = new UtilizadoresApp();
        }

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public UtilizadoresController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        private ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            set
            {
                _signInManager = value;
            }
        }

        private ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        // GET: Admin/Utilizadores
        public ActionResult Index()
        {
            ViewBag.Roles = ToJson(_rolesApp.ListarRoles());
            return View();
        }

        [HttpPost]
        public JsonResult FiltrarUtilizadores(string f)
        {
            var res = _utilizadoresApp.FiltrarUtilizadores(f);
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult PesquisarUsuarios(string f)
        {
            var res = _utilizadoresApp.FiltrarUtilizadores(f);
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> CriarUtilizadorAsync(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Login, Email = model.Email, Nome = model.Nome };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {

                    await UserManager.AddToRolesAsync(user.Id, model.Roles.ToArray());

                    return Json(new AppResultado().Good($"Utilizador {user.Nome} criado com exito."),
                        JsonRequestBehavior.AllowGet);
                }

                return Json(new AppResultado().Bad($"Erro ao tentar criar utilizador {": " + result.Errors.FirstOrDefault()}"),
                        JsonRequestBehavior.AllowGet);
            }

            return Json(new AppResultado().Bad($"Formulario inválido, valide e tente novamente."),
                        JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ActualizaRoles(string idUsuario, List<string> roles)
        {
            return Json(_utilizadoresApp.ModificarRoles(idUsuario, roles));
        }

        [HttpPost]
        public JsonResult ActualizaNome(string idUsuario, string nome, string login)
        {

            return Json(_utilizadoresApp.ModificarNome(idUsuario, nome, login));
        }

        [HttpPost]
        public JsonResult DesactivarUsuario(string idUsuario)
        {
            //_userManager.

            return Json(new { });
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<JsonResult> ActualizarSenha(string idUsuario, string senha)
        {
            //var utilizador = _utilizadoresApp.UtilizadorById(Guid.Parse(idUsuario));

            var user = await UserManager.FindByIdAsync(idUsuario);

            if (user == null)
            {
                return Json(new AppResultado().Bad("Usuario nao encontrado."));
            }

            string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);

            var result = await UserManager.ResetPasswordAsync(user.Id, code, senha);
            if (result.Succeeded)
            {
                return Json(new AppResultado().Good("Senha actualizada com exito."));
            }

            return Json(new AppResultado().Bad($"Error ao actualizar senha: {result.Errors.FirstOrDefault()}"));
        }
    }
}

minamb/Views/Shared/Footer.cshtml
<footer class="main-footer">
    @*<iframe
        allow="microphone;"
        width="350"
        height="430"
        src="https://console.dialogflow.com/api-client/demo/embedded/b524ad02-48f7-42b0-82e1-ce94ae39a001">
    </iframe>*@
    <div class="pull-right hidden-xs">
        <b>v</b> @ViewContext.Controller.GetType().Assembly.GetName().Version
    </div>
    <div class="text-center">
        <strong>&copy; @DateTime.Now.Year </strong> Gestão de Ministérios by <a target="_blank" href="#">KAS Tecnologias</a>
    </div>
   
</footer>

minamb/Views/Shared/Header.cshtml
<header class="header dark-bg">
    <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Fechar menu" data-placement="bottom"><i class="icon_menu"></i></div>
    </div>

    <!--logo start-->
    <a href="index.html" class="logo">MIN <span class="lite">SAÚDE</span></a>
    <!--logo end-->
    <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">

            <!-- task notificatoin start -->
            <!-- task notificatoin end -->
            <!-- inbox notificatoin start-->

            <!-- inbox notificatoin end -->
            <!-- alert notification start-->
 
            <!-- alert notification end-->
            <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="profile-ava">
                        <img alt="" src="~/assets/img/avatar-mini2.jpg">
                    </span>
                    <span class="username">@User.Identity.GetNome()</span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <li class="eborder-top">
                        <a href="#"><i class="icon_profile"></i>&nbsp;Meu perfíl</a>
                    </li>
                    <li>
                        <a href="@Url.Action("LogOff","Account", new {Area = ""})"><i class="icon_key_alt"></i>&nbsp;Sair</a>
                    </li>
                </ul>
            </li>
            <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
    </div>
</header>

minamb/Views/Shared/Navegacao.cshtml
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="treeview">
                <a href="@Url.Action("Index","Home",new {Area =""})">
                    <i class="fa fa-home"></i>
                    <span>Inicio</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span>Entidades</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Funcionarios", "Funcionario", new {Area = ""})"><i class="fa fa-edit"></i>Funcionários</a></li>
                    <li><a href="@Url.Action("Index","Utilizadores", new {Area = ""})"><i class="fa fa-users"></i> <span>Gestão de Usuários</span></a></li>
                    <li><a href="@Url.Action("Requerentes", "Requerente", new {Area = ""})"><i class="fa fa-edit"></i>Requerentes</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-retweet"></i>
                    <span>Processos</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index", "Home", new {Area = ""})"><i class="fa fa-bookmark"></i>Amostras</a></li>
                    <li><a href="@Url.Action("Index", "Home", new {Area = ""})"><i class="fa fa-asterisk"></i>Solicitação de análises</a></li>

                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-credit-card-alt"></i>
                    <span>Caixa</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-bookmark"></i>Sub-menu</a></li>
                    <li><a href="#"><i class="fa fa-asterisk"></i>Sub-menu</a></li>

                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-database"></i>
                    <span>Relatórios</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-bookmark"></i>Sub-menu</a></li>
                    <li><a href="#"><i class="fa fa-asterisk"></i>Sub-menu</a></li>

                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-cogs"></i>
                    <span>Definições</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-bookmark"></i>Sub-menu</a></li>
                    <li><a href="#"><i class="fa fa-asterisk"></i>Sub-menu</a></li>

                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

minamb/Views/Shared/Utilizador.cshtml
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-user-circle-o"></i>
        <span class="hidden-xs">@User.Identity.GetNome()</span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header" style="color: white">
            <h2>
            </h2>
            <h3>
                <small class="h3">@User.Identity.GetNome()</small>
            </h3>
        </li>
        <!-- Menu Body -->
        <li class="user-footer">
            <div class="pull-left">
                <a class="btn btn-default btn-flat"><i class="fa fa-user-circle-o"></i>&nbsp;Perfil</a>
            </div>
            <div class="pull-right">
                <a href="@Url.Action("LogOff","Account", new {Area = ""})" class="btn btn-default btn-flat"><i class="fa fa-sign-out"></i>&nbsp;Sair</a>
            </div>
        </li>
    </ul>
</li>

minamb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MINSA - @ViewBag.Title</title>

    <link href="~/assets/plugins/PleaseWait/please-wait.css" rel="stylesheet" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @*<link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />*@
    <script src="~/assets/plugins/PleaseWait/please-wait.js"></script>
    <link href="~/assets/assets2/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/assets2/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/assets2/bower_components/Ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/assets/assets2/dist/css/AdminLTE.min.css" rel="stylesheet" />
    @*<link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />*@
    @*<link href="~/assets/css/AdminLTE.min.css" rel="stylesheet" />*@
    <link href="~/assets/css/skin-blue.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/highcharts/css/highcharts.css" rel="stylesheet" />
    <link href="~/assets/plugins/iCheck/all.css" rel="stylesheet" />
    <link href="~/assets/plugins/SweetAlert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/assets/css/Chart.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/bootstrap-slider/slider.css" rel="stylesheet" />
    <link href="~/assets/css/Rating.css" rel="stylesheet" />
    <link href="~/assets/css/_all-skins.css" rel="stylesheet" />
    @*<link href="~/assets/css/Ionicons/css/ionicons.min.css" rel="stylesheet" />*@
    @*<link href="~/assets/css/_all-skins.min.css" rel="stylesheet" />*@
    <link href="~/assets/css/jquery-jvectormap.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/assets/css/morris.css" rel="stylesheet" />
    @*<link href="~/Assets/css/treeView.css" rel="stylesheet" />*@
    <link href="~/assets/css/daterangepicker.css" rel="stylesheet" />
    @*<link href="~/Assets/plugins/pNotify/PNotifyBrightTheme.min.css" rel="stylesheet" />*@
    <link href="~/assets/plugins/pNotify/pnotify.custom.min.css" rel="stylesheet" />
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="~/assets/css/bootstrap-vue.min.css" rel="stylesheet" />
    <link href="~/assets/css/cssColapse.css" rel="stylesheet" />
    <link href="~/assets/css/vuesax.css" rel="stylesheet" />




</head>
<body class="sidebar-mini skin-green-light">
    <script src="~/assets/js/loader.js"></script>
    <script src="~/assets/js/vue.js"></script>
    @*<script src="~/assets/js/vue.min.js"></script>*@
    <script src="~/assets/js/moment.js"></script>



    <!-- use the latest vue-select release -->
    <script src="~/assets/js/vue-select.js"></script>
    <link rel="stylesheet" href="~/Assets/css/vue-select.css">

    <link href="~/assets/css/selectize.css" rel="stylesheet" />



    <!-- or point to a specific vue-select release -->
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","Home", new {Area = ""})" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>Minsa</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Ministério da </b>Saúde</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu" id="app1">
                    <ul class="nav navbar-nav">
                        @*@Html.Partial("Cliente")*@


                        @Html.Partial("Utilizador")

                    </ul>
                </div>
            </nav>
        </header>
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        @Html.Partial("Navegacao")
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <i class="fa-2x @ViewBag.Icon" style="margin-right: 10px;margin-left: 10px"></i>
                    <span class="h1">@ViewBag.Title</span>
                </h1>
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
                <!-- Default box -->
                <!-- /.box -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        @Html.Partial("Footer")

    </div>

    <script src="~/assets/assets2/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/assets2/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/assets/assets2/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/assets2/dist/js/adminlte.min.js"></script>
    <script src="~/assets/assets2/dist/js/demo.js"></script>
    @*<script src="~/Assets/js/Chart.bundle.min.js"></script>*@
    @*<script src="~/assets/js/jquery.min.js"></script>*@
    @*<script src="~/assets/js/bootstrap.min.js"></script>*@
    @*<script src="~/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>*@
    @*<script src="~/assets/js/fastclick.js"></script>
        <script src="~/assets/js/adminlte.min.js"></script>*@
    <script src="~/assets/plugins/SweetAlert2/sweetalert2.min.js"></script>
    <script src="~/assets/plugins/pNotify/PNotify.min.js"></script>
    <script src="~/assets/js/UI.v2.js"></script>
    <script src="~/assets/js/bootstrap-vue.min.js"></script>
    <script src="~/assets/js/jquery.knob.js"></script>
    <script src="~/assets/js/jquery.sparkline.js"></script>
    <script src="~/assets/js/jquery.sparkline.min.js"></script>
    <script src="~/assets/plugins/highcharts/highcharts.js"></script>
    <script src="~/assets/js/jquery.slimscroll.js"></script>
    <script src="~/assets/js/jquery.slimscroll.min.js"></script>
    <script src="~/assets/plugins/bootstrap-slider/bootstrap-slider.js"></script>
    <script src="~/assets/plugins/iCheck/icheck.min.js"></script>
    <script src="~/assets/js/vuesax.umd.min.js"></script>
    <script src="~/assets/js/star-rating.min.js"></script>
    <script src="~/assets/js/jquery-jvectormap.js"></script>
    <script src="~/assets/js/bootstrap-datepicker.min.js"></script>
    <script src="~/assets/js/daterangepicker.js"></script>

    <script src="~/assets/js/bootstrap3-wysihtml5.all.min.js"></script>
    <script src="~/assets/js/jquery.slimscroll.min.js"></script>
    <script src="~/assets/js/selectize.min.js"></script>
    <script src="~/assets/js/appSetting.js"></script>
    <script src="https://cdn.ckeditor.com/4.11.1/standard/ckeditor.js"></script>
    <script src="https://cdn.jsdelivr.net/vuejs-paginator/2.0.0/vuejs-paginator.min.js"></script>
    <script src="~/assets/js/moment.js"></script>

    @*<script type="text/javascript" src="~/Scripts/jquery-3.3.1.min.js"></script>*@



    @if (TempData["Erro"] != null)
    {
        <script>
            MsgErro('@(TempData["Erro"].ToString())');
        </script>
    }

    @if (TempData["Ok"] != null)
    {
        <script>
            MsgOk('@(TempData["Ok"].ToString())');
        </script>
    }

    @if (TempData["Alert"] != null)
    {
        <script>
            MsgAlert('@(TempData["Alert"].ToString())');
        </script>
    }

    @if (TempData["Info"] != null)
    {
        <script>
            MsgInfo('@(TempData["Info"].ToString())');
        </script>
    }
    @RenderSection("scripts", false)
</body>
</html>